#!/usr/bin/env python
"""Task 32 (a): one significance table for every deployable signal.

For every deployable signal, cell and quota:
- the realised gain minus random's, in loss units and as a share of the all-cheap loss, with its 95% paired
  unit-bootstrap interval over every draw (125's `paired_gain` section: 1,000 draws, none dropped);
- next to it, the official nDG with its interval under the 25% prize filter, as the benchmark tables report it.

Signals: the two gates, the four feature routers (R1), the pixel router (R2), detector uncertainty, CHEAP criticality
and ego speed. Ego speed is 125's trivial baseline, scored through the same protocol, and has no official nDG row.
Cells: the ten core cells and the nuPlan real-perception cells. Nothing is recomputed here.

Writes results/final/significance_table.csv and docs/significance_table.md.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
FINAL = ROOT / "results" / "final"
SIGNALS = ["gate_ridge", "gate_gbm", "R1_mlp_reg", "R1_mlp_clf", "R1_gbm_reg", "R1_gbm_clf", "R2_cnn_clf",
           "uncertainty", "criticality_cheap", "trivial_ego_speed"]
KEY = ["track", "geometry", "system", "target", "signal", "quota"]


def official(FINAL):
    def rd(name, real):
        x = pd.read_csv(FINAL / name, keep_default_na=False, na_values=[""], float_precision="round_trip")
        x = x[(x.split == "test") & x.quota.notna()]
        return x[x.track == "nuPlan"] if real else x[x.track != "nuPlan"]
    t = pd.concat([rd("benchmark_table.csv", False), rd("benchmark_table_routers.csv", False),
                   rd("benchmark_table_nuplan_real.csv", True)], ignore_index=True)
    t["geometry"] = t.geometry.fillna("n/a").replace("", "n/a")
    return t[KEY + ["eta", "eta_lo", "eta_hi", "boot_dropped"]].rename(
        columns={"eta": "ndg_official", "eta_lo": "ndg_lo_filtered", "eta_hi": "ndg_hi_filtered",
                 "boot_dropped": "ndg_draws_dropped_by_filter"})


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--final", default=str(FINAL), help="the results/final directory to read (e.g. a snapshot)")
    ap.add_argument("--out", default=None, help="write the CSV here only (no markdown); default: results/final and docs")
    args = ap.parse_args()
    FINAL_ = Path(args.final)
    h = pd.read_csv(FINAL_ / "statistics_hardening.csv", keep_default_na=False, na_values=[""],
                    float_precision="round_trip", low_memory=False)
    p = h[(h.section == "paired_gain") & h.signal.isin(SIGNALS)].copy()
    p["geometry"] = p.geometry.fillna("n/a").replace("", "n/a")
    p["quota"] = p.quota.astype(float)
    off = official(FINAL_)
    off["quota"] = off.quota.astype(float)
    t = p.merge(off, on=KEY, how="left", validate="one_to_one")
    cols = KEY + ["n_test_units", "n_test_frames", "available", "undefined_reason", "all_cheap_loss", "gain",
                  "gain_random", "delta_vs_random", "delta_lo_all_draws", "delta_hi_all_draws", "delta_share_all_cheap",
                  "delta_share_lo_all_draws", "delta_share_hi_all_draws", "beats_random_all_draws",
                  "ndg", "ndg_official", "ndg_lo_filtered", "ndg_hi_filtered", "ndg_draws_dropped_by_filter",
                  "delta_lo_filtered", "delta_hi_filtered", "beats_random_filtered"]
    t = t[cols]
    lo, hi = t.delta_lo_all_draws.astype(float), t.delta_hi_all_draws.astype(float)
    t["interval"] = np.where(lo > 0, "above random", np.where(hi < 0, "below random",
                             np.where(lo.notna(), "includes 0", "n/a")))
    # the official nDG must be the one 125 recomputed, where both exist
    both = t.ndg.notna() & t.ndg_official.notna()
    assert np.allclose(t.ndg[both].astype(float), t.ndg_official[both].astype(float), rtol=0, atol=1e-12), \
        "125's nDG differs from the official table's"
    t = t.sort_values(["track", "geometry", "system", "signal", "quota"]).reset_index(drop=True)
    if args.out:
        t.to_csv(args.out, index=False)
        print(t.groupby(["signal", "interval"]).size().unstack(fill_value=0).to_string())
        return
    t.to_csv(FINAL / "significance_table.csv", index=False)

    md = ["# Significance table (generated by scripts/162_significance_table.py — do not edit by hand)", "",
          "Realised gain of each deployable signal minus random's on test units, in loss units and as a share of the "
          "all-cheap loss. The interval is the 95% paired unit bootstrap over every draw (1,000 draws, none dropped; "
          "`statistics_hardening.csv`, section `paired_gain`). nDG and its interval are the official ones, under the "
          "25% prize filter. Ego speed is scored through the same protocol and has no official nDG row.", "",
          "## Counts: where the paired interval lies, per signal and quota", "",
          "| signal | quota | above random | includes 0 | below random | n/a |", "|---|---|---|---|---|---|"]
    for (s, q), x in t.groupby(["signal", "quota"], sort=False):
        c = x.interval.value_counts()
        md.append(f"| {s} | {q:.0%} | {c.get('above random', 0)} | {c.get('includes 0', 0)} | "
                  f"{c.get('below random', 0)} | {c.get('n/a', 0)} |")
    md += ["", "## Every row", "",
           "| cell | signal | quota | gain − random [95% all draws] | share of all-cheap loss [95%] | nDG [95% filtered] |",
           "|---|---|---|---|---|---|"]

    def f(x, d=4):
        return "—" if x is None or not np.isfinite(float(x)) else f"{float(x):+.{d}f}"
    for _, r in t.iterrows():
        cell = f"{r.track} {r.geometry} {r.system} {r.target}"
        nd = ("—" if not np.isfinite(float(r.ndg_official)) else
              f"{float(r.ndg_official):.3f} [{float(r.ndg_lo_filtered):.3f}, {float(r.ndg_hi_filtered):.3f}]")
        md.append(f"| {cell} | {r.signal} | {r.quota:.0%} | {f(r.delta_vs_random)} [{f(r.delta_lo_all_draws)}, "
                  f"{f(r.delta_hi_all_draws)}] | {f(100 * float(r.delta_share_all_cheap), 2)}% "
                  f"[{f(100 * float(r.delta_share_lo_all_draws), 2)}, {f(100 * float(r.delta_share_hi_all_draws), 2)}] "
                  f"| {nd} |")
    (ROOT / "docs" / "significance_table.md").write_text("\n".join(md) + "\n")
    print(t.groupby(["signal", "interval"]).size().unstack(fill_value=0).to_string())
    print("wrote", FINAL / "significance_table.csv")


if __name__ == "__main__":
    main()
